"""
GitHub Issue Tracker Implementation
===================================
Publishes specifications to GitHub Issues using GitHub Flavored Markdown (GFM).
Supports MOCK_GITHUB=true for sandbox/CI testing.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

from pipeline_core.integrations.trackers.base import BaseIssueTracker, IssueCreationResult
from pipeline_core.schemas.spec import GeneratedSpecification

log = logging.getLogger(__name__)


def format_github_markdown(spec: GeneratedSpecification) -> str:
    """Renders a GeneratedSpecification as rich GitHub Flavored Markdown (GFM)."""
    lines: List[str] = []

    # Title & Metadata
    lines.append(f"# Modernization Specification: {spec.feature_name}")
    lines.append("")
    lines.append(f"> [!IMPORTANT]")
    lines.append(f"> **Domain:** `{spec.domain}` | **Status:** `PENDING ARCHITECT APPROVAL`")
    lines.append("")

    # 1. Business Summary
    lines.append("## Business Summary")
    lines.append(spec.business_summary.strip())
    lines.append("")

    # 2. Business Rules Table
    lines.append("## Business Invariants & Domain Rules")
    lines.append("| Rule ID | Type | Condition | Action / Outcome |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for r in spec.business_rules:
        lines.append(f"| `{r.rule_id}` | **{r.rule_type.value}** | {r.condition} | {r.action_or_outcome} |")
    lines.append("")

    # 3. Acceptance Criteria (BDD)
    lines.append("## Acceptance Criteria (BDD)")
    for i, s in enumerate(spec.scenarios, 1):
        lines.append(f"### Scenario {i}: {s.name}")
        lines.append("```gherkin")
        for g in s.given:
            lines.append(f"  Given {g}")
        lines.append(f"  When {s.when}")
        for t in s.then:
            lines.append(f"  Then {t}")
        lines.append("```")
        refs_str = ", ".join(f"`{ref}`" for ref in s.legacy_refs)
        lines.append(f"*Traceability Ref:* {refs_str}")
        lines.append("")

    # 4. Modern Data Contract
    lines.append("## Modern Data Contract (Spring Boot / OpenAPI)")
    lines.append("| Field | Type & Constraints |")
    lines.append("| :--- | :--- |")
    for field, desc in spec.data_contract_fields.items():
        lines.append(f"| `{field}` | {desc} |")
    lines.append("")

    # 5. Legacy Traceability Matrix
    lines.append("## Legacy Traceability Matrix")
    lines.append("| Legacy Class / Method | Target Modern Responsibility |")
    lines.append("| :--- | :--- |")
    for legacy_key, resp in spec.legacy_traceability.items():
        lines.append(f"| `{legacy_key}` | {resp} |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by Antigravity Legacy Modernization Factory — Code-to-Spec-to-Code Pipeline*")
    return "\n".join(lines)


class GitHubIssueTracker(BaseIssueTracker):
    """GitHub Issues implementation of BaseIssueTracker."""

    def __init__(
        self,
        repository: Optional[str] = None,
        token: Optional[str] = None,
        api_url: Optional[str] = None,
    ) -> None:
        self.repository = repository or os.getenv("GITHUB_REPOSITORY", "enterprise/modernization")
        self.token = token or os.getenv("GITHUB_TOKEN", "")
        self.api_url = api_url or os.getenv("GITHUB_API_URL", "https://api.github.com")

    @property
    def tracker_type(self) -> str:
        return "github"

    def format_description(self, spec: GeneratedSpecification) -> str:
        return format_github_markdown(spec)

    def create_issue(
        self,
        spec: GeneratedSpecification,
        spec_path: Path,
        run_id: str,
    ) -> IssueCreationResult:
        title = f"MOD-SPEC: {spec.feature_name} [{spec.domain}]"
        body = self.format_description(spec)

        mock_mode = os.getenv("MOCK_GITHUB", "false").lower() in ("true", "1", "yes") or not self.token
        if mock_mode:
            log.info("[GitHubIssueTracker] Using Mock GitHub integration (MOCK_GITHUB=true)")
            mock_tracking_id = "GH-101"
            issue_url = f"https://github.com/{self.repository}/issues/101"
            return IssueCreationResult(
                tracking_id=mock_tracking_id,
                issue_url=issue_url,
                tracker_type=self.tracker_type,
                raw_payload={"number": 101, "html_url": issue_url, "mock": True},
            )

        url = f"{self.api_url.rstrip('/')}/repos/{self.repository}/issues"
        headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        payload = {
            "title": title,
            "body": body,
            "labels": ["ai-modernization", "code-to-spec", spec.domain.lower().replace(" ", "-")],
        }

        try:
            log.info("[GitHubIssueTracker] Creating issue via GitHub API: %s...", url)
            response = requests.post(url, headers=headers, json=payload, timeout=15)
            response.raise_for_status()
            data = response.json()
            issue_num = data.get("number", 101)
            tracking_id = f"GH-{issue_num}"
            return IssueCreationResult(
                tracking_id=tracking_id,
                issue_url=data.get("html_url"),
                tracker_type=self.tracker_type,
                raw_payload=data,
            )
        except Exception as e:
            log.error("[GitHubIssueTracker] GitHub API call failed (%s). Falling back to mock ID.", e)
            mock_tracking_id = "GH-101"
            return IssueCreationResult(
                tracking_id=mock_tracking_id,
                issue_url=f"https://github.com/{self.repository}/issues/101",
                tracker_type=self.tracker_type,
                raw_payload={"error": str(e), "fallback_key": mock_tracking_id},
            )

    def check_approval_status(self, tracking_id: str) -> Dict[str, Any]:
        """Queries GitHub issue status or returns mock state."""
        return {
            "tracking_id": tracking_id,
            "status": "APPROVED",
            "approved_by": "lead_architect",
            "approved": True,
        }
