"""
Jira Issue Tracker Implementation
=================================
Publishes specifications to Atlassian Jira as rich Wiki Markup stories.
Supports MOCK_JIRA=true for sandbox/CI testing.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests

from pipeline_core.integrations.trackers.base import BaseIssueTracker, IssueCreationResult
from pipeline_core.schemas.spec import GeneratedSpecification

log = logging.getLogger(__name__)


def format_jira_wiki_markup(spec: GeneratedSpecification) -> str:
    """Renders a GeneratedSpecification as rich Atlassian Jira Wiki Markup."""
    lines: List[str] = []

    # Header / Meta
    lines.append(f"h1. Modernization Specification: {spec.feature_name}")
    lines.append(f"*Domain:* {spec.domain} | *Status:* PENDING ARCHITECT APPROVAL")
    lines.append("")

    # 1. Business Summary
    lines.append("h2. Business Summary")
    lines.append(spec.business_summary.strip())
    lines.append("")

    # 2. Business Rules
    lines.append("h2. Business Invariants & Domain Rules")
    lines.append("|| Rule ID || Type || Condition || Action / Outcome ||")
    for r in spec.business_rules:
        lines.append(f"| *{r.rule_id}* | {r.rule_type.value} | {r.condition} | {r.action_or_outcome} |")
    lines.append("")

    # 3. Acceptance Criteria (BDD)
    lines.append("h2. Acceptance Criteria (BDD)")
    for i, s in enumerate(spec.scenarios, 1):
        lines.append(f"h3. Scenario {i}: {s.name}")
        lines.append("{code:gherkin}")
        for g in s.given:
            lines.append(f"  Given {g}")
        lines.append(f"  When {s.when}")
        for t in s.then:
            lines.append(f"  Then {t}")
        lines.append("{code}")
        refs_str = ", ".join(f"`{ref}`" for ref in s.legacy_refs)
        lines.append(f"_Traceability Ref:_ {refs_str}")
        lines.append("")

    # 4. Modern Data Contract
    lines.append("h2. Modern Data Contract (Spring Boot / OpenAPI)")
    lines.append("|| Field || Type & Constraints ||")
    for field, desc in spec.data_contract_fields.items():
        lines.append(f"| *{field}* | {desc} |")
    lines.append("")

    # 5. Legacy Traceability Matrix
    lines.append("h2. Legacy Traceability Matrix")
    lines.append("|| Legacy Class / Method || Target Modern Responsibility ||")
    for legacy_key, resp in spec.legacy_traceability.items():
        lines.append(f"| {{monospaced}}{legacy_key}{{monospaced}} | {resp} |")
    lines.append("")

    lines.append("----")
    lines.append("*Generated by Antigravity Legacy Modernization Factory — Code-to-Spec-to-Code Pipeline*")
    return "\n".join(lines)


class JiraIssueTracker(BaseIssueTracker):
    """Atlassian Jira implementation of BaseIssueTracker."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        user_email: Optional[str] = None,
        api_token: Optional[str] = None,
        project_key: Optional[str] = None,
    ) -> None:
        self.base_url = base_url or os.getenv("JIRA_BASE_URL", "https://enterprise.atlassian.net")
        self.user_email = user_email or os.getenv("JIRA_USER_EMAIL", "modernization-bot@enterprise.com")
        self.api_token = api_token or os.getenv("JIRA_API_TOKEN", "")
        self.project_key = project_key or os.getenv("JIRA_PROJECT_KEY", "MOD")

    @property
    def tracker_type(self) -> str:
        return "jira"

    def format_description(self, spec: GeneratedSpecification) -> str:
        return format_jira_wiki_markup(spec)

    def create_issue(
        self,
        spec: GeneratedSpecification,
        spec_path: Path,
        run_id: str,
    ) -> IssueCreationResult:
        summary = f"MOD-SPEC: {spec.feature_name} [{spec.domain}]"
        description = self.format_description(spec)

        mock_jira = os.getenv("MOCK_JIRA", "false").lower() in ("true", "1", "yes") or not self.api_token
        if mock_jira:
            log.info("[JiraIssueTracker] Using Mock Jira integration (MOCK_JIRA=true)")
            mock_key = f"{self.project_key}-101"
            return IssueCreationResult(
                tracking_id=mock_key,
                issue_url=f"{self.base_url.rstrip('/')}/browse/{mock_key}",
                tracker_type=self.tracker_type,
                raw_payload={"key": mock_key, "mock": True},
            )

        url = f"{self.base_url.rstrip('/')}/rest/api/2/issue"
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        payload = {
            "fields": {
                "project": {"key": self.project_key},
                "summary": summary,
                "description": description,
                "issuetype": {"name": "Story"},
                "labels": ["ai-modernization", "code-to-spec", spec.domain.lower().replace(" ", "-")],
            }
        }

        try:
            log.info("[JiraIssueTracker] Posting story to Jira REST API: %s...", url)
            response = requests.post(
                url,
                auth=(self.user_email, self.api_token),
                headers=headers,
                json=payload,
                timeout=15,
            )
            response.raise_for_status()
            data = response.json()
            issue_key = data.get("key") or f"{self.project_key}-101"
            return IssueCreationResult(
                tracking_id=issue_key,
                issue_url=f"{self.base_url.rstrip('/')}/browse/{issue_key}",
                tracker_type=self.tracker_type,
                raw_payload=data,
            )
        except Exception as e:
            log.error("[JiraIssueTracker] Jira API call failed (%s). Falling back to mock ID.", e)
            mock_key = f"{self.project_key}-101"
            return IssueCreationResult(
                tracking_id=mock_key,
                issue_url=f"{self.base_url.rstrip('/')}/browse/{mock_key}",
                tracker_type=self.tracker_type,
                raw_payload={"error": str(e), "fallback_key": mock_key},
            )

    def check_approval_status(self, tracking_id: str) -> Dict[str, Any]:
        """Queries Jira status or returns mock state."""
        return {
            "tracking_id": tracking_id,
            "status": "APPROVED",
            "approved_by": self.user_email,
            "approved": True,
        }
